# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FBFeed' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'

  # Pods for FBFeed

  target 'FBFeedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FBFeedUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
